//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface CBaseFile : NSObject
{
}

+ (BOOL)RemoveFile:(id)arg1;
+ (void)EnsureCreateParentDir:(id)arg1;
+ (BOOL)CreateFolder:(id)arg1;
+ (BOOL)FileExist:(id)arg1;
+ (BOOL)CopyFile:(id)arg1 To:(id)arg2;

@end

