//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface JTCaptureSetting : NSObject
{
    NSString *_fileNamePrefix;
}

+ (id)sharedInstance;
@property(retain, nonatomic) NSString *fileNamePrefix; // @synthesize fileNamePrefix=_fileNamePrefix;
- (void).cxx_destruct;
- (id)defaultValueOfThemeName;
- (id)defaultValueOfChannel;
- (id)defaultValueOfFileNamePrefix;
- (id)defaultValueOfSavePath;
- (BOOL)defaultValueOfRunAlone;
- (BOOL)defaultValueOfResolution;
- (unsigned long long)defaultValueOfFileType;
- (BOOL)defaultValueOfPlaySound;
@property(retain, nonatomic) NSString *themeName;
@property(nonatomic, getter=isRunAlone) BOOL runAlone;
@property(retain, nonatomic) NSString *channel;
@property(retain, nonatomic) NSString *lastSavePath;
@property(nonatomic) unsigned long long fileType;
@property(nonatomic, getter=isHighResolution) BOOL highResolution;
@property(nonatomic, getter=isPlaySound) BOOL playSound;
- (void)dealloc;
- (id)init;

@end

