//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class JTCaptureWindowInfo;

@protocol JTCaptureViewDelegate <NSObject>
- (void)gotActiveWindowInfo:(JTCaptureWindowInfo *)arg1;
- (JTCaptureWindowInfo *)windowInfoAtPostion:(struct CGPoint)arg1;
- (void)selectionDidChange;
- (void)mouseLocationDidUpdate:(struct CGPoint)arg1 needShowMagnifier:(BOOL)arg2;
- (void)didConfirmSelection;
@end

