//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

//#import "NSObject.h"

@interface JTCaptureRequest : NSObject
{
    BOOL _showSwitch;
    BOOL _needSelectSavePath;
    JTCaptureRequest* _delegate;
}

+ (id)sharedInstance;
@property(nonatomic) BOOL needSelectSavePath; // @synthesize needSelectSavePath=_needSelectSavePath;
@property(nonatomic) BOOL showSwitch; // @synthesize showSwitch=_showSwitch;
@property(nonatomic) __weak JTCaptureRequest* delegate; // @synthesize delegate=_delegate;
- (void)cxx_destruct;
- (void)dealloc;
- (id)init;

@end

