//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

//#import "NSObject.h"

#import "JTCaptureWindowControllerDelegate-Protocol.h"
#import "JTSwitchMangagerDelegate-Protocol.h"
#import "JTCaptureRequest.h"

@class JTCaptureRequest, JTSwitchMangager, NSMutableArray, NSString;

@interface JTCaptureManager : NSObject <JTCaptureWindowControllerDelegate, JTSwitchMangagerDelegate>
{
    BOOL _isCapturing;
    JTCaptureRequest *_request;
    JTCaptureRequest* _delegate;
    NSMutableArray *_windowControllers;
    unsigned long long _screenCount;
    JTSwitchMangager *_switchManager;
}

+ (id)sharedInstance;
@property(retain, nonatomic) JTSwitchMangager *switchManager; // @synthesize switchManager=_switchManager;
@property(nonatomic) unsigned long long screenCount; // @synthesize screenCount=_screenCount;
@property(retain, nonatomic) NSMutableArray *windowControllers; // @synthesize windowControllers=_windowControllers;
@property(retain, nonatomic) JTCaptureRequest* delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) JTCaptureRequest *request; // @synthesize request=_request;
@property(nonatomic) BOOL isCapturing; // @synthesize isCapturing=_isCapturing;
- (void)cxx_destruct;
- (void)handleReceivedSelectDidBeginNotification:(id)arg1;
- (void)handleScreenParametersNotification:(id)arg1;
- (void)handleCaptureCancelNotification:(id)arg1;
- (void)addObserver;
- (void)defaultSaveImage:(id)arg1 isHighResolution:(BOOL)arg2;
- (void)saveImage:(id)arg1 isHighResolution:(BOOL)arg2;
- (void)writeImageToPasteboard:(id)arg1;
- (void)playSound;
- (void)captureFrame:(struct CGRect)arg1 screen:(id)arg2;
- (void)clean;
- (void)cleanCaptureWindow;
- (void)prepareToRecord;
- (void)changeToRecord;
- (void)captureDidFinishWithImage:(id)arg1 needSave:(BOOL)arg2 isHighResolution:(BOOL)arg3;
- (void)captureDidCancel;
- (void)cancelCapture;
- (BOOL)startCaptureByRequest:(id)arg1;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

