//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface JTCaptureThemeManager : NSObject
{
    NSString *_themeName;
    NSString *_themePath;
}

+ (id)sharedInstance;
@property(retain, nonatomic) NSString *themePath; // @synthesize themePath=_themePath;
@property(retain, nonatomic) NSString *themeName; // @synthesize themeName=_themeName;
- (void).cxx_destruct;
- (id)objectWithKey:(id)arg1;
- (id)themePathWithThemeName:(id)arg1;
- (void)setupCurrentTheme;
- (BOOL)themedEnableWithKey:(id)arg1;
- (float)themedWeightWithKey:(id)arg1;
- (struct CGSize)themedSizeWithKey:(id)arg1;
- (struct CGSize)themedMarginWithKey:(id)arg1;
- (struct CGRect)themedFrameWithKey:(id)arg1;
- (id)themedImageWithKey:(id)arg1;
- (id)themedFontWithKey:(id)arg1;
- (id)themedColorWithKey:(id)arg1;
- (BOOL)changeThemeTo:(id)arg1;
- (void)resetTheme;
- (id)nameArrayOfAvailableThemes;
- (BOOL)isJietuTheme;
- (id)init;

@end

