//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSViewController.h"

#import "JTToolbarWindowControllerDelegate.h"

@class JTEditView, NSImage, NSImageView, NSString;

@interface JTEditViewController : NSViewController <JTToolbarWindowControllerDelegate>
{
    NSImageView *_backgroundImageView;
    JTEditView *_editView;
    NSImage *_backgroundImage;
}

@property(nonatomic) __weak NSImage *backgroundImage; // @synthesize backgroundImage=_backgroundImage;
@property(retain, nonatomic) JTEditView *editView; // @synthesize editView=_editView;
@property(retain, nonatomic) NSImageView *backgroundImageView; // @synthesize backgroundImageView=_backgroundImageView;
- (void).cxx_destruct;
- (id)imageEdited;
- (void)undo;
- (void)widthDidChange:(unsigned long long)arg1;
- (void)colorDidChange:(id)arg1;
- (void)graphTypeDidChange:(long long)arg1;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

