//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSView.h"

@class NSColor, NSImage, NSTrackingArea;

@interface JTIntroduceView : NSView
{
    BOOL _isHover;
    NSColor *_hoverColor;
    NSColor *_backgroundColor;
    NSImage *_normalImage;
    NSImage *_hoverImage;
    NSTrackingArea *_trackingArea;
}

@property(retain, nonatomic) NSTrackingArea *trackingArea; // @synthesize trackingArea=_trackingArea;
@property(retain, nonatomic) NSImage *hoverImage; // @synthesize hoverImage=_hoverImage;
@property(retain, nonatomic) NSImage *normalImage; // @synthesize normalImage=_normalImage;
@property(retain, nonatomic) NSColor *backgroundColor; // @synthesize backgroundColor=_backgroundColor;
@property(retain, nonatomic) NSColor *hoverColor; // @synthesize hoverColor=_hoverColor;
@property(nonatomic) BOOL isHover; // @synthesize isHover=_isHover;
- (void).cxx_destruct;
- (void)openURL:(id)arg1;
- (void)mouseUp:(id)arg1;
- (void)mouseDown:(id)arg1;
- (void)mouseExited:(id)arg1;
- (void)mouseEntered:(id)arg1;
- (void)drawRect:(struct CGRect)arg1;
- (BOOL)mouseInView;
- (void)updateTrackingAreas;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;

@end

