//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <JietuFramework/JTPopoverLineColorView.h>

@class JTPopoverButton, JTPopoverMenu;

@interface JTPopoverLineColorViewForQQ : JTPopoverLineColorView
{
    JTPopoverButton *_colorButton;
    JTPopoverButton *_pullDownArrowButton;
    JTPopoverMenu *_colorMenu;
}

@property(retain, nonatomic) JTPopoverMenu *colorMenu; // @synthesize colorMenu=_colorMenu;
@property(retain, nonatomic) JTPopoverButton *pullDownArrowButton; // @synthesize pullDownArrowButton=_pullDownArrowButton;
@property(retain, nonatomic) JTPopoverButton *colorButton; // @synthesize colorButton=_colorButton;
- (void).cxx_destruct;
- (void)configAppearanceAndLayout;
- (void)hideMenu;
- (void)colorButtonDidClick:(id)arg1;
- (void)showPopoverColorMenu:(id)arg1;
- (id)selectedColor;
- (void)setSelectedColor:(id)arg1;
- (id)defaultColor;
- (void)drawRect:(struct CGRect)arg1;
- (void)setupPullDownArrowButton;
- (void)setupColorMenu;
- (void)setupColorButton;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;

@end

