//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSView.h"

@class JTPopoverLineWidthButton, NSMutableArray;

@interface JTPopoverLineWidthView : NSView
{
    id <JTPopoverLineWidthViewDelegate> _delegate;
    NSMutableArray *_buttonArray;
    JTPopoverLineWidthButton *_selectedButton;
}

@property(nonatomic) __weak JTPopoverLineWidthButton *selectedButton; // @synthesize selectedButton=_selectedButton;
@property(retain, nonatomic) NSMutableArray *buttonArray; // @synthesize buttonArray=_buttonArray;
@property(nonatomic) __weak id <JTPopoverLineWidthViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (id)normalImageNameArray;
- (id)selectedImageNameArray;
- (id)buttonWidthValueArray;
- (id)buttonFrameArray;
- (void)configAppearanceAndLayout;
- (void)onLineWidthButtonClicked:(id)arg1;
@property(nonatomic) unsigned long long width;
@property(readonly, nonatomic) unsigned long long defaultWidth;
- (void)drawRect:(struct CGRect)arg1;
- (void)setupButtons;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;

@end

