//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <JietuFramework/JceObjectV2.h>

@class NSString;

@interface JTSTStatProtocol_Function : JceObjectV2
{
    unsigned int jcev2_p_0_r_iProtocol;
    unsigned int jcev2_p_1_r_iKey;
    unsigned int jcev2_p_2_o_iValueI;
    unsigned int jcev2_p_3_o_iValueII;
    unsigned int jcev2_p_4_o_iValueIII;
    NSString *jcev2_p_5_o_sValueI;
    NSString *jcev2_p_6_o_sValueII;
    NSString *jcev2_p_7_o_sValueIII;
}

+ (id)jceType;
+ (void)initialize;
+ (id)mtthdInstance;
@property(retain, nonatomic, getter=jce_sValueIII, setter=setJce_sValueIII:) NSString *jcev2_p_7_o_sValueIII; // @synthesize jcev2_p_7_o_sValueIII;
@property(retain, nonatomic, getter=jce_sValueII, setter=setJce_sValueII:) NSString *jcev2_p_6_o_sValueII; // @synthesize jcev2_p_6_o_sValueII;
@property(retain, nonatomic, getter=jce_sValueI, setter=setJce_sValueI:) NSString *jcev2_p_5_o_sValueI; // @synthesize jcev2_p_5_o_sValueI;
@property(nonatomic, getter=jce_iValueIII, setter=setJce_iValueIII:) unsigned int jcev2_p_4_o_iValueIII; // @synthesize jcev2_p_4_o_iValueIII;
@property(nonatomic, getter=jce_iValueII, setter=setJce_iValueII:) unsigned int jcev2_p_3_o_iValueII; // @synthesize jcev2_p_3_o_iValueII;
@property(nonatomic, getter=jce_iValueI, setter=setJce_iValueI:) unsigned int jcev2_p_2_o_iValueI; // @synthesize jcev2_p_2_o_iValueI;
@property(nonatomic, getter=jce_iKey, setter=setJce_iKey:) unsigned int jcev2_p_1_r_iKey; // @synthesize jcev2_p_1_r_iKey;
@property(nonatomic, getter=jce_iProtocol, setter=setJce_iProtocol:) unsigned int jcev2_p_0_r_iProtocol; // @synthesize jcev2_p_0_r_iProtocol;
- (void)dealloc;
- (id)init;

@end

