//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableDictionary, NSString;

@interface JTStatisticManager : NSObject
{
    NSMutableDictionary *_statInfoDic;
    NSString *_statFilePath;
}

+ (id)defaultStatisticManager;
@property(retain, nonatomic) NSString *statFilePath; // @synthesize statFilePath=_statFilePath;
@property(retain, nonatomic) NSMutableDictionary *statInfoDic; // @synthesize statInfoDic=_statInfoDic;
- (void).cxx_destruct;
- (void)statisticEvent:(unsigned long long)arg1 withValue:(id)arg2;
- (void)statisticEvent:(unsigned long long)arg1;
- (void)resetStatistic;
- (id)statInfo;
- (void)synchronizeStatInfo;
- (void)updateStatInfo;
- (void)clearStatInfo;
- (void)dealloc;
- (id)init;

@end

