//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <JietuFramework/JceObjectV2.h>

@class JTSTStatComm, NSArray;

@interface JTSTStat : JceObjectV2
{
    JTSTStatComm *jcev2_p_0_r_stComm;
    NSArray *jcev2_p_21_o_vProtocols_Function__b0x9i_VOJTSTStatProtocol_Function;
}

+ (id)jceType;
+ (void)initialize;
+ (id)mtthdInstance;
@property(retain, nonatomic, getter=jce_vProtocols_Function, setter=setJce_vProtocols_Function:) NSArray *jcev2_p_21_o_vProtocols_Function__b0x9i_VOJTSTStatProtocol_Function; // @synthesize jcev2_p_21_o_vProtocols_Function__b0x9i_VOJTSTStatProtocol_Function;
@property(retain, nonatomic, getter=jce_stComm, setter=setJce_stComm:) JTSTStatComm *jcev2_p_0_r_stComm; // @synthesize jcev2_p_0_r_stComm;
- (void)dealloc;
- (id)init;

@end

