//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSButton.h"

#import "CAAnimationDelegate.h"

@class NSImage, NSImageView, NSString;

@interface JTSwitchButton : NSButton <CAAnimationDelegate>
{
    BOOL _isCapturing;
    BOOL _postedAction;
    id <JTSwitchButtonDelegate> _delegate;
    NSImageView *_throbberImageView;
    NSImage *_firstImage;
    NSImage *_throbberImage;
}

@property(nonatomic) BOOL postedAction; // @synthesize postedAction=_postedAction;
@property(retain, nonatomic) NSImage *throbberImage; // @synthesize throbberImage=_throbberImage;
@property(retain, nonatomic) NSImage *firstImage; // @synthesize firstImage=_firstImage;
@property(retain, nonatomic) NSImageView *throbberImageView; // @synthesize throbberImageView=_throbberImageView;
@property(nonatomic) BOOL isCapturing; // @synthesize isCapturing=_isCapturing;
@property(nonatomic) __weak id <JTSwitchButtonDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)animationDidStop:(id)arg1 finished:(BOOL)arg2;
- (void)animationDidStart:(id)arg1;
- (void)setupThrobberImageAnimation;
- (void)mouseDown:(id)arg1;
- (void)drawRect:(struct CGRect)arg1;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

