//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSPanel.h"

#import "JTSwitchButtonDelegate.h"
#import "NSAnimationDelegate.h"

@class JTSwitchButton, NSButton, NSString, NSTrackingArea, NSView, NSViewAnimation;

@interface JTSwitchPanel : NSPanel <JTSwitchButtonDelegate, NSAnimationDelegate>
{
    id <JTSwitchPanelDelegate> _panelDelegate;
    NSView *_showContentView;
    NSButton *_pullDownButton;
    JTSwitchButton *_switchButton;
    NSTrackingArea *_trackingArea;
    NSViewAnimation *_hideBarAnimation;
    NSViewAnimation *_showBarAnimation;
    struct CGRect _showFrame;
    struct CGRect _hideFrame;
}

+ (id)initWithFrame:(struct CGRect)arg1 screen:(id)arg2;
@property(nonatomic) struct CGRect hideFrame; // @synthesize hideFrame=_hideFrame;
@property(nonatomic) struct CGRect showFrame; // @synthesize showFrame=_showFrame;
@property(retain, nonatomic) NSViewAnimation *showBarAnimation; // @synthesize showBarAnimation=_showBarAnimation;
@property(retain, nonatomic) NSViewAnimation *hideBarAnimation; // @synthesize hideBarAnimation=_hideBarAnimation;
@property(retain, nonatomic) NSTrackingArea *trackingArea; // @synthesize trackingArea=_trackingArea;
@property(retain, nonatomic) JTSwitchButton *switchButton; // @synthesize switchButton=_switchButton;
@property(retain, nonatomic) NSButton *pullDownButton; // @synthesize pullDownButton=_pullDownButton;
@property(retain, nonatomic) NSView *showContentView; // @synthesize showContentView=_showContentView;
@property(nonatomic) __weak id <JTSwitchPanelDelegate> panelDelegate; // @synthesize panelDelegate=_panelDelegate;
- (void).cxx_destruct;
- (void)animationDidEnd:(id)arg1;
- (void)mouseMoved:(id)arg1;
- (void)mouseEntered:(id)arg1;
- (void)updateTrackingAreas;
- (void)pullDownAction:(id)arg1;
- (void)pullUpAction:(id)arg1;
- (void)changeToRecord;
- (void)prepareToRecord;
- (void)showWithAnimation:(BOOL)arg1;
- (void)dealloc;
- (id)initWithContentRect:(struct CGRect)arg1 styleMask:(unsigned long long)arg2 backing:(unsigned long long)arg3 defer:(BOOL)arg4 screen:(id)arg5;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

