//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSWindowController.h"

#import "JTPopoverWindowControllerDelegate.h"
#import "JTToolbarViewDelegate.h"

@class JTPopoverWindowController, JTToolbarView, NSColor, NSString;

@interface JTToolbarWindowController : NSWindowController <JTToolbarViewDelegate, JTPopoverWindowControllerDelegate>
{
    BOOL _enableUndo;
    id <JTToolbarWindowControllerDelegate> _delegate;
    NSColor *_backgroundColor;
    JTToolbarView *_toolbarView;
    JTPopoverWindowController *_popoverWindowController;
    struct CGPoint _position;
}

@property(retain, nonatomic) JTPopoverWindowController *popoverWindowController; // @synthesize popoverWindowController=_popoverWindowController;
@property(retain, nonatomic) JTToolbarView *toolbarView; // @synthesize toolbarView=_toolbarView;
@property(nonatomic) BOOL enableUndo; // @synthesize enableUndo=_enableUndo;
@property(retain, nonatomic) NSColor *backgroundColor; // @synthesize backgroundColor=_backgroundColor;
@property(nonatomic) struct CGPoint position; // @synthesize position=_position;
@property(nonatomic) __weak id <JTToolbarWindowControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)handleChangeThemeNotification:(id)arg1;
- (void)unregisterForChangeThemeNotification;
- (void)registerForChangeThemeNotification;
- (void)fontSizeDidChange:(unsigned long long)arg1;
- (void)widthDidChange:(unsigned long long)arg1;
- (void)colorDidChange:(id)arg1;
- (void)showPopoverViewType:(long long)arg1 width:(unsigned long long)arg2 color:(id)arg3;
- (void)showPopoverViewType:(long long)arg1;
- (void)undo;
- (void)graphTypeDidChange:(long long)arg1;
- (void)onUndoRedoCheckNotification:(id)arg1;
- (void)beginCreateItem:(id)arg1;
- (void)focusItemDidChange:(id)arg1;
- (void)dealloc;
- (id)initWithOrigin:(struct CGPoint)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

