//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface JTWUPUtilities : NSObject
{
}

+ (int)operatingSystemDigit;
+ (id)operatingSystemLanguage;
+ (id)operatingSystemVersion;
+ (unsigned long long)clientVersion;
+ (id)operatingSystem;
+ (id)supplyID;
+ (id)formattedVersion;
+ (id)buildVersion;
+ (id)bundleShortVersion;
+ (id)version;
+ (id)UUID;

@end

