//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <JietuFramework/MttWupAgent.h>

@interface MttStatAgent : MttWupAgent
{
}

- (void)stat:(id)arg1 withCompleteHandle:(CDUnknownBlockType)arg2;
- (id)serverURLs;
- (id)init;

@end

