//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSColor.h"

@interface NSColor (HexColorAddition)
+ (unsigned int)hx_hexValueToUnsigned:(id)arg1;
+ (id)hx_hexStringTransformFromThreeCharacters:(id)arg1;
+ (id)hx_colorWith8BitRed:(long long)arg1 green:(long long)arg2 blue:(long long)arg3 alpha:(double)arg4;
+ (id)hx_colorWith8BitRed:(long long)arg1 green:(long long)arg2 blue:(long long)arg3;
+ (id)hx_colorWithHexString:(id)arg1 alpha:(double)arg2;
+ (id)hx_colorWithHexString:(id)arg1;
@end

