//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSString.h"

@interface NSString (CCCrypt)
- (id)Mtt_encryptWithDES:(const void *)arg1 CCOperation:(unsigned int)arg2;
- (id)Mtt_hexStringOfSHA1;
- (id)Mtt_hexStringOfMD5;
- (id)Mtt_sha1;
- (id)Mtt_md5;
@end

