//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSData, NSMutableArray, NSString, WupEncryptKey;

@interface WUPHTTPRequestInfo : NSObject
{
    NSString *_funcName;
    NSData *_uniPacketData;
    NSMutableArray *_serverURLs;
    WupEncryptKey *_encryptKey;
}

@property(retain, nonatomic) WupEncryptKey *encryptKey; // @synthesize encryptKey=_encryptKey;
@property(retain, nonatomic) NSMutableArray *serverURLs; // @synthesize serverURLs=_serverURLs;
@property(copy, nonatomic) NSData *uniPacketData; // @synthesize uniPacketData=_uniPacketData;
@property(copy, nonatomic) NSString *funcName; // @synthesize funcName=_funcName;
- (void).cxx_destruct;
- (id)init;

@end

