//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface Utils : NSObject
{
}

+ (long long)integralValue:(double)arg1;
+ (struct CGSize)integralSize:(struct CGSize)arg1;
+ (struct CGPoint)integralPoint:(struct CGPoint)arg1;
+ (struct CGRect)integralRect:(struct CGRect)arg1;
+ (struct CGImage *)CGImageFromNSImage:(id)arg1;
+ (id)combinedImage:(id)arg1 bottomImage:(id)arg2 operation:(unsigned long long)arg3;
+ (id)combinedImage:(id)arg1 bottomImage:(id)arg2;
+ (id)image:(id)arg1 cropLeftCap:(double)arg2 rightCap:(double)arg3;
+ (id)image:(id)arg1 leftCapWidth:(float)arg2 middleWidth:(float)arg3 rightCapWidth:(float)arg4;
+ (id)stringForDrawingType:(int)arg1;
+ (id)colorForIndex:(long long)arg1;
+ (id)colorForIdentifier:(id)arg1;
+ (int)CALineJionToCGLineJoin:(id)arg1;
+ (int)CALineCapToCGLineCap:(id)arg1;
+ (struct CGColor *)newCGColorCreateFromNSColor:(id)arg1 colorSpace:(struct CGColorSpace *)arg2;
+ (struct CGColor *)newCGColorCreateDirectlyFromNSColor:(id)arg1;

@end

