//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSPanel.h"

@class NSImage, NSScreen, WWCaptureContentView, WWGlassImageView;

@interface WWCaptureWindow : NSPanel
{
    BOOL _isScreenArg;
    WWCaptureContentView *_captureContentView;
    WWGlassImageView *_backgroundImageView;
    NSImage *_backgroundImage;
    NSScreen *_windowScreen;
    struct CGRect _contentRect;
}

@property struct CGRect contentRect; // @synthesize contentRect=_contentRect;
@property __weak NSScreen *windowScreen; // @synthesize windowScreen=_windowScreen;
@property BOOL isScreenArg; // @synthesize isScreenArg=_isScreenArg;
@property(retain) NSImage *backgroundImage; // @synthesize backgroundImage=_backgroundImage;
@property(retain) WWGlassImageView *backgroundImageView; // @synthesize backgroundImageView=_backgroundImageView;
@property(retain) WWCaptureContentView *captureContentView; // @synthesize captureContentView=_captureContentView;
- (void).cxx_destruct;
- (void)rightMouseDown:(id)arg1;
- (void)refreshShowInfo;
- (id)imageForContentFrame;
- (void)updateCaptureBackground;
- (void)cancelAllSeletedView;
- (BOOL)canBecomeKeyWindow;
- (BOOL)canBecomeMainWindow;
- (BOOL)becomeFirstResponder;
- (void)keyDown:(id)arg1;
- (void)internalInitBackgrondView;
- (id)initWithContentRect:(struct CGRect)arg1 styleMask:(unsigned long long)arg2 backing:(unsigned long long)arg3 defer:(BOOL)arg4 screen:(id)arg5;
- (id)initWithContentRect:(struct CGRect)arg1 styleMask:(unsigned long long)arg2 backing:(unsigned long long)arg3 defer:(BOOL)arg4;

@end

