//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSView.h"

@class NSImage, NSMutableArray, NSScreen, WWCaptureGeometryView;

@interface WWCaptureGrabAreaView : NSView
{
    BOOL _isNeedShowCorner;
    int _dragType;
    int _viewMode;
    int _borderWidth;
    NSMutableArray *_geometryViews;
    WWCaptureGeometryView *_selectedView;
    id <WWCaptureAreaViewDelegate> _delegate;
    NSImage *_mosaicImage;
    NSScreen *_captureScreen;
    struct CGPoint _clickPoint;
}

@property(retain) NSScreen *captureScreen; // @synthesize captureScreen=_captureScreen;
@property(retain) NSImage *mosaicImage; // @synthesize mosaicImage=_mosaicImage;
@property int borderWidth; // @synthesize borderWidth=_borderWidth;
@property __weak id <WWCaptureAreaViewDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain) WWCaptureGeometryView *selectedView; // @synthesize selectedView=_selectedView;
@property(retain) NSMutableArray *geometryViews; // @synthesize geometryViews=_geometryViews;
@property(nonatomic) BOOL isNeedShowCorner; // @synthesize isNeedShowCorner=_isNeedShowCorner;
@property int viewMode; // @synthesize viewMode=_viewMode;
@property int dragType; // @synthesize dragType=_dragType;
@property struct CGPoint clickPoint; // @synthesize clickPoint=_clickPoint;
- (void).cxx_destruct;
- (void)generalDragAreaMosaicImage;
- (void)forceGeneralDragAreaMosaicImage;
- (void)hideAllSelectedViewAndSelf;
- (void)setFrame:(struct CGRect)arg1;
- (void)makeGrabAreaViewKey:(id)arg1;
- (void)selectedGeometyViewChanged:(id)arg1;
- (void)viewBecomePaintingMode:(id)arg1;
- (void)deleteSelectedGeometryView;
- (id)hitTestSCGeometryView:(struct CGPoint)arg1;
- (void)setSelectedGeometryView:(id)arg1;
- (void)frameDidChange:(id)arg1;
- (void)mouseDragged:(id)arg1;
- (void)drawGeometry:(id)arg1;
- (float)cornerRadius;
- (struct CGRect)convertInvalidRectToFrame:(struct CGRect)arg1;
- (struct CGRect)convertToinvalidRect:(struct CGRect)arg1;
- (struct CGRect)invalidFrame;
- (int)dragType:(struct CGPoint)arg1;
- (struct CGRect)cornerArea:(int)arg1;
- (struct CGRect)dragArea:(int)arg1;
- (struct CGRect)commonArea:(int)arg1 xSpace:(float)arg2 ySpace:(float)arg3 xOffset:(float)arg4 yOffset:(float)arg5;
- (void)resetCursorRects;
- (void)keyDown:(id)arg1;
- (void)mouseMoved:(id)arg1;
- (void)mouseDown:(id)arg1;
- (void)mouseUp:(id)arg1;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;

@end

