//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSView.h"

#import "WWCaptureAreaViewDelegate.h"

@class NSMutableArray, NSString, NSTrackingArea, WWCaptureControlContainView, WWCaptureGrabAreaView, WWCaptureReadingGlassView;

@interface WWCaptureContentView : NSView <WWCaptureAreaViewDelegate>
{
    BOOL _isGrabFinished;
    BOOL _isHideBorder;
    BOOL _isEnterWindow;
    BOOL _firstEnter;
    WWCaptureGrabAreaView *_grabAreaView;
    WWCaptureReadingGlassView *_glassView;
    NSMutableArray *_windowList;
    long long _windowPid;
    WWCaptureControlContainView *_sizeInfoView;
    NSTrackingArea *_trackingArea;
    struct CGPoint _clickPoint;
    struct CGRect _windowFrame;
    struct CGRect _sizeInfoRect;
}

@property BOOL firstEnter; // @synthesize firstEnter=_firstEnter;
@property(nonatomic) BOOL isEnterWindow; // @synthesize isEnterWindow=_isEnterWindow;
@property BOOL isHideBorder; // @synthesize isHideBorder=_isHideBorder;
@property(retain) NSTrackingArea *trackingArea; // @synthesize trackingArea=_trackingArea;
@property(retain) WWCaptureControlContainView *sizeInfoView; // @synthesize sizeInfoView=_sizeInfoView;
@property struct CGRect sizeInfoRect; // @synthesize sizeInfoRect=_sizeInfoRect;
@property BOOL isGrabFinished; // @synthesize isGrabFinished=_isGrabFinished;
@property long long windowPid; // @synthesize windowPid=_windowPid;
@property struct CGRect windowFrame; // @synthesize windowFrame=_windowFrame;
@property(retain) NSMutableArray *windowList; // @synthesize windowList=_windowList;
@property(retain) WWCaptureReadingGlassView *glassView; // @synthesize glassView=_glassView;
@property(retain) WWCaptureGrabAreaView *grabAreaView; // @synthesize grabAreaView=_grabAreaView;
@property struct CGPoint clickPoint; // @synthesize clickPoint=_clickPoint;
- (void).cxx_destruct;
- (void)setSizeInfoFiled:(struct CGRect)arg1;
- (void)hideGlassReadingView;
- (void)showGlassReadingViewAtpoint:(struct CGPoint)arg1;
- (void)refreshShowInfo:(id)arg1;
- (void)cancelAllSeletedView;
- (BOOL)performKeyEquivalent:(id)arg1;
- (void)setSizeInfo:(struct CGRect)arg1;
- (BOOL)acceptsFirstMouse:(id)arg1;
- (void)hideGlassView;
- (void)showGlassViewAtPoint:(struct CGPoint)arg1;
- (struct CGRect)pointArea:(struct CGPoint)arg1 windowPid:(long long *)arg2;
- (void)mouseExited:(id)arg1;
- (void)mouseEntered:(id)arg1;
- (void)mouseMoved:(id)arg1;
- (void)mouseUp:(id)arg1;
- (void)mouseDragged:(id)arg1;
- (void)rightMouseDown:(id)arg1;
- (void)mouseDown:(id)arg1;
- (void)drawRect:(struct CGRect)arg1;
- (void)updateTrackingAreas;
- (void)updateGlassView;
- (void)refreshWindowList;
- (id)initWithFrame:(struct CGRect)arg1 image:(id)arg2 withScreen:(id)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

