//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <ScreenCapture/WWCaptureGeometryView.h>

@class NSTextView;

@interface WWCaptureTextFieldView : WWCaptureGeometryView
{
    NSTextView *_innerTextView;
}

+ (void)setCurrentTextFieldView:(id)arg1;
+ (id)currentTextFieldView;
@property(retain) NSTextView *innerTextView; // @synthesize innerTextView=_innerTextView;
- (void).cxx_destruct;
- (BOOL)hasContent;
- (void)viewMouseDragged:(id)arg1;
- (BOOL)invalidRectContainPoint:(struct CGPoint)arg1;
- (void)resetCursorRects;
- (void)setSelected:(BOOL)arg1;
- (void)setLineWidth:(float)arg1;
- (void)setTextSize:(int)arg1;
- (void)setLineColor:(id)arg1;
- (void)viewMouseDown:(id)arg1;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;

@end

