//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableArray;

@interface WWCaptureWindowManager : NSObject
{
    NSMutableArray *_windowControllerArray;
    id _caller;
}

+ (id)shareInstance;
@property __weak id caller; // @synthesize caller=_caller;
@property(retain) NSMutableArray *windowControllerArray; // @synthesize windowControllerArray=_windowControllerArray;
- (void).cxx_destruct;
- (void)refreshShowInfo;
- (id)captureScreenWindows;
- (void)captureCrossScreen:(id)arg1;
- (void)saveImageToFile:(id)arg1;
- (id)startChooseURL;
- (void)caputreSaveToLobal:(id)arg1;
- (void)captureSave:(id)arg1;
- (void)grabAreaChange:(id)arg1;
- (void)captureFinished:(id)arg1;
- (void)hideToolKit:(id)arg1;
- (void)showToolKit:(id)arg1;
- (void)internalStartCapture:(id)arg1 withHide:(BOOL)arg2;
- (void)hideStartCapture:(id)arg1;
- (void)startCapture:(id)arg1;
- (void)cleanController;
- (void)dealloc;
- (id)init;

@end

