//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <ScreenCapture/WWCaptureGeometryView.h>

@class NSBezierPath;

@interface WWCaptureArrowView : WWCaptureGeometryView
{
    NSBezierPath *_path;
    struct CGPoint _tailPoint;
    struct CGPoint _headPoint;
}

@property(retain) NSBezierPath *path; // @synthesize path=_path;
@property struct CGPoint headPoint; // @synthesize headPoint=_headPoint;
@property struct CGPoint tailPoint; // @synthesize tailPoint=_tailPoint;
- (void).cxx_destruct;
- (BOOL)invalidRectContainPoint:(struct CGPoint)arg1;
- (void)resetCursorRects;
- (void)viewMouseDragged:(id)arg1;
- (void)viewMouseDown:(id)arg1;
- (void)drawRect:(struct CGRect)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

