//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSView.h"

@class NSColor, NSImageView;

@interface WWCaptureColorView : NSView
{
    BOOL _selected;
    BOOL _mouseInView;
    id <WWCaptureColorViewDelegate> _colorViewDelegate;
    NSColor *_color;
    NSView *_colorView;
    NSImageView *_chooseImageView;
    long long _trackingTag;
}

@property long long trackingTag; // @synthesize trackingTag=_trackingTag;
@property BOOL mouseInView; // @synthesize mouseInView=_mouseInView;
@property(retain) NSImageView *chooseImageView; // @synthesize chooseImageView=_chooseImageView;
@property(retain) NSView *colorView; // @synthesize colorView=_colorView;
@property(nonatomic) BOOL selected; // @synthesize selected=_selected;
@property(retain, nonatomic) NSColor *color; // @synthesize color=_color;
@property __weak id <WWCaptureColorViewDelegate> colorViewDelegate; // @synthesize colorViewDelegate=_colorViewDelegate;
- (void).cxx_destruct;
- (void)layout;
- (void)checkChooseImageViewHidden;
- (void)mouseExited:(id)arg1;
- (void)mouseMoved:(id)arg1;
- (void)mouseEntered:(id)arg1;
- (void)mouseDown:(id)arg1;
- (void)updateTrackingAreas;
- (void)_init;
- (void)dealloc;
- (void)awakeFromNib;
- (id)initWithFrame:(struct CGRect)arg1;
- (id)init;

@end

