//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface WWCaptureScreenHelper : NSObject
{
}

+ (id)captureImageWithFrame:(struct CGRect)arg1 size:(struct CGSize)arg2;
+ (BOOL)haveSeparateSapces;
+ (void)button:(id)arg1 setTitleColor:(id)arg2;
+ (double)backingScaleFactorForScreen:(id)arg1;
+ (double)backingScaleFactor;
+ (id)soundNamed:(id)arg1;
+ (struct CGPoint)convertBaseLocationToScreen:(struct CGPoint)arg1 window:(id)arg2;
+ (struct CGPoint)convertScreenLocationToBase:(struct CGPoint)arg1 window:(id)arg2;
+ (void)endCaptureDisplay;
+ (long long)intersectScreenWithRect:(struct CGRect)arg1 intersection:(struct CGRect *)arg2;
+ (struct CGRect)convertScreenToDeviceRect:(struct CGRect)arg1;
+ (struct CGPoint)convertScreenToDevicePoint:(struct CGPoint)arg1;
+ (struct CGRect)convertDeviceToScreenRect:(struct CGRect)arg1;
+ (struct CGPoint)convertDeviceToScreenPoint:(struct CGPoint)arg1;
+ (struct CGRect)nearScreenFrameByPoint:(struct CGPoint)arg1;
+ (struct CGRect)screenFrameByPoint:(struct CGPoint)arg1 pid:(long long *)arg2;
+ (struct CGRect)screenFrameOfMouse;
+ (BOOL)isScreenFrame:(struct CGRect)arg1;
+ (unsigned int)currentDisplayID;
+ (struct CGRect)captureDeviceScreenFrame;
+ (struct CGRect)captureScreenFrame;
+ (BOOL)beginCaptureDisplay;
+ (BOOL)isSystemVersionUpper:(id)arg1;
+ (id)currentVersionString;
+ (BOOL)isEqualOrUpper10134;
+ (BOOL)isUpper1070;

@end

