//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <ScreenCapture/WWCaptureGeometryView.h>

@class NSImage, NSMutableArray;

@interface WWCapturePaintBrushView : WWCaptureGeometryView
{
    NSMutableArray *_pointsArray;
    NSImage *_backImage;
    struct CGPoint _origin;
    struct CGRect _imageInvalidRect;
}

@property struct CGPoint origin; // @synthesize origin=_origin;
@property struct CGRect imageInvalidRect; // @synthesize imageInvalidRect=_imageInvalidRect;
@property(retain) NSImage *backImage; // @synthesize backImage=_backImage;
@property(retain) NSMutableArray *pointsArray; // @synthesize pointsArray=_pointsArray;
- (void).cxx_destruct;
- (void)resetCursorRects;
- (void)redrawImage;
- (void)setLineColor:(id)arg1;
- (void)setLineWidth:(float)arg1;
- (BOOL)invalidRectContainPoint:(struct CGPoint)arg1;
- (void)updateInvalidRect;
- (void)viewMouseDown:(id)arg1;
- (void)drawRect:(struct CGRect)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

