//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <ScreenCapture/WWCaptureGeometryView.h>

@class NSBezierPath, NSImage, NSMutableArray;

@interface WWCaptureMosaicView : WWCaptureGeometryView
{
    NSMutableArray *_pointsArray;
    NSImage *_showImage;
    NSBezierPath *_path;
    NSImage *_tempMosaicImage;
    double _filterRadius;
    struct CGPoint _origin;
    struct CGRect _imageInvalidRect;
}

@property double filterRadius; // @synthesize filterRadius=_filterRadius;
@property(retain) NSImage *tempMosaicImage; // @synthesize tempMosaicImage=_tempMosaicImage;
@property(retain) NSBezierPath *path; // @synthesize path=_path;
@property struct CGRect imageInvalidRect; // @synthesize imageInvalidRect=_imageInvalidRect;
@property struct CGPoint origin; // @synthesize origin=_origin;
@property(retain) NSImage *showImage; // @synthesize showImage=_showImage;
@property(retain) NSMutableArray *pointsArray; // @synthesize pointsArray=_pointsArray;
- (void).cxx_destruct;
- (BOOL)invalidRectContainViewPoint:(struct CGPoint)arg1;
- (BOOL)invalidRectContainPoint:(struct CGPoint)arg1;
- (void)updateInvalidRect;
- (void)mosaicAtPoint:(struct CGPoint)arg1;
- (void)addPoint:(struct CGPoint)arg1;
- (void)viewMouseDown:(id)arg1;
- (void)drawRect:(struct CGRect)arg1;
- (id)mosaicImageWithImage:(id)arg1 rect:(struct CGRect)arg2 tileSize:(int)arg3;
- (void)setLineWidth:(float)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

