//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@protocol WWCaptureManagerDelegate <NSObject>

- (void)grabDidFinish;

- (void)grabDidFinishSaveAs:(NSData *)imageData;

@end

@interface WWCaptureManager : NSObject
{
    BOOL _isCapturing;
    id <WWCaptureManagerDelegate> _delegate;
}

+ (id)shareInstance;
@property BOOL isCapturing; // @synthesize isCapturing=_isCapturing;
@property __weak id <WWCaptureManagerDelegate> delegate; // @synthesize delegate=_delegate;
- (void)cxx_destruct;
- (id)captureScreenWindows;
- (void)grabDidFinish;
- (void)grabDidFinishSaveAs:(id)arg1;
- (void)hideStartCaptureWithDelegate:(id)arg1 fileType:(unsigned long long)arg2;
- (void)startCaptureWithDelegate:(id)arg1 fileType:(unsigned long long)arg2;
- (void)_refreshShowInfo;
- (void)refreshShowInfo;

@end

