//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSTextView.h"

#import "NSTextViewDelegate.h"

@class NSColor, NSMutableDictionary, NSString, NSTrackingArea;

@interface WWCaptureTextView : NSTextView <NSTextViewDelegate>
{
    id _localEventMonitor;
    BOOL _drawFrame;
    NSMutableDictionary *_markedAttr;
    NSTrackingArea *_trackArea;
    NSColor *_frameColor;
    struct CGPoint _ptStart;
    struct CGPoint _ptOrigin;
}

@property(retain, nonatomic) NSColor *frameColor; // @synthesize frameColor=_frameColor;
@property struct CGPoint ptOrigin; // @synthesize ptOrigin=_ptOrigin;
@property struct CGPoint ptStart; // @synthesize ptStart=_ptStart;
@property BOOL drawFrame; // @synthesize drawFrame=_drawFrame;
@property(retain) NSTrackingArea *trackArea; // @synthesize trackArea=_trackArea;
@property(retain) NSMutableDictionary *markedAttr; // @synthesize markedAttr=_markedAttr;
- (void).cxx_destruct;
- (void)mouseUp:(id)arg1;
- (void)mouseDown:(id)arg1;
- (void)unselectTextView;
- (void)shiftKeyResponder;
- (BOOL)resignFirstResponder;
- (BOOL)becomeFirstResponder;
- (void)invalidateSelection;
- (BOOL)textView:(id)arg1 doCommandBySelector:(SEL)arg2;
- (id)textView:(id)arg1 shouldChangeTypingAttributes:(id)arg2 toAttributes:(id)arg3;
- (BOOL)textView:(id)arg1 shouldChangeTextInRange:(struct _NSRange)arg2 replacementString:(id)arg3;
- (void)test:(id)arg1;
- (void)textViewDidChangeTypingAttributes:(id)arg1;
- (void)drawRect:(struct CGRect)arg1;
- (void)cursorUpdate:(id)arg1;
- (void)mouseExited:(id)arg1;
- (void)mouseEntered:(id)arg1;
- (void)updateTrackingAreas;
- (void)uninstallTrackingArea;
- (void)installTrackingArea;
- (void)setTextColor:(id)arg1;
- (void)setFont:(id)arg1;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

