//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class YascaControlPanel;

@protocol YascaControlPanelDelegate <NSObject>

@optional
- (void)controlPanel:(YascaControlPanel *)arg1 saveButtonClick:(id)arg2;
- (void)controlPanel:(YascaControlPanel *)arg1 colorButtonClickedWithIndex:(long long)arg2;
- (void)controlPanel:(YascaControlPanel *)arg1 didChooseFontSize:(long long)arg2;
- (void)controlPanel:(YascaControlPanel *)arg1 lineSizeButtonClickedWithMode:(int)arg2;
- (void)controlPanelDidConfirm:(YascaControlPanel *)arg1;
- (void)controlPanelDidCancel:(YascaControlPanel *)arg1;
- (void)controlPanel:(YascaControlPanel *)arg1 shapeButtonClickedWithType:(int)arg2;
@end

