//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSView.h"

@class NSImage;

@interface YascaControlPanelBackgroundView : NSView
{
    NSImage *_croppedImageSingle;
    NSImage *_croppedImageDouble;
}

- (void).cxx_destruct;
- (id)croppedImageDouble;
- (id)croppedImageSingle;
- (void)drawRect:(struct CGRect)arg1;

@end

