//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSButton.h"

@interface YascaControlPanelButton : NSButton
{
    long long _previousState;
    BOOL _stateSetBySelf;
}

- (void)drawRect:(struct CGRect)arg1;
- (void)setStateBySelf:(long long)arg1;
- (void)setState:(long long)arg1;
- (void)mouseMoved:(id)arg1;
- (void)mouseExited:(id)arg1;
- (void)mouseEntered:(id)arg1;
- (void)mouseDown:(id)arg1;
- (id)initWithCoder:(id)arg1;

@end

