//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSViewController.h"

#import "WWCaptureColorViewDelegate.h"
#import "WWCaptureIconfontButtonDelegate.h"

@class NSPopUpButton, NSString, NSView, WWCaptureColorView, WWCaptureIconfontButton;

@interface YascaControlPanel : NSViewController <WWCaptureIconfontButtonDelegate, WWCaptureColorViewDelegate>
{
    NSView *_lineSizeView;
    NSView *_fontSizeView;
    NSView *_colorView;
    WWCaptureIconfontButton *_recButton;
    WWCaptureIconfontButton *_roundButton;
    WWCaptureIconfontButton *_arrowButton;
    WWCaptureIconfontButton *_bushButton;
    WWCaptureIconfontButton *_fontButton;
    WWCaptureIconfontButton *_cancelButton;
    WWCaptureIconfontButton *_confirmButton;
    WWCaptureIconfontButton *_saveToClipboardButton;
    WWCaptureIconfontButton *_mosaicButton;
    NSString *_fileName;
    id <YascaControlPanelDelegate> _delegate;
    WWCaptureIconfontButton *_smallSizeButton;
    WWCaptureIconfontButton *_middleSizeButton;
    WWCaptureIconfontButton *_bigSizeButton;
    WWCaptureColorView *_redColorButton;
    WWCaptureColorView *_yellowColorButton;
    WWCaptureColorView *_blueColorButton;
    WWCaptureColorView *_greenColorButton;
    WWCaptureColorView *_blackColorButton;
    WWCaptureColorView *_grayColorButton;
    WWCaptureColorView *_whiteColorButton;
    NSPopUpButton *_fontSizeMenu;
}

@property __weak NSPopUpButton *fontSizeMenu; // @synthesize fontSizeMenu=_fontSizeMenu;
@property __weak WWCaptureColorView *whiteColorButton; // @synthesize whiteColorButton=_whiteColorButton;
@property __weak WWCaptureColorView *grayColorButton; // @synthesize grayColorButton=_grayColorButton;
@property __weak WWCaptureColorView *blackColorButton; // @synthesize blackColorButton=_blackColorButton;
@property __weak WWCaptureColorView *greenColorButton; // @synthesize greenColorButton=_greenColorButton;
@property __weak WWCaptureColorView *blueColorButton; // @synthesize blueColorButton=_blueColorButton;
@property __weak WWCaptureColorView *yellowColorButton; // @synthesize yellowColorButton=_yellowColorButton;
@property __weak WWCaptureColorView *redColorButton; // @synthesize redColorButton=_redColorButton;
@property __weak WWCaptureIconfontButton *bigSizeButton; // @synthesize bigSizeButton=_bigSizeButton;
@property __weak WWCaptureIconfontButton *middleSizeButton; // @synthesize middleSizeButton=_middleSizeButton;
@property __weak WWCaptureIconfontButton *smallSizeButton; // @synthesize smallSizeButton=_smallSizeButton;
@property __weak id <YascaControlPanelDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)dealloc;
- (id)buttonGroupForView:(id)arg1;
- (id)animationInfoForView:(id)arg1;
- (struct CGRect)viewFrame:(id)arg1 isStart:(BOOL)arg2;
- (void)onColorViewClicked:(id)arg1;
- (void)saveButtonClicked:(id)arg1;
- (void)fontSizeDidChoosed:(id)arg1;
- (void)lineSizeButtonClicked:(id)arg1;
- (void)confirmButtonClicked:(id)arg1;
- (void)cancelButtonClicked:(id)arg1;
- (void)shapeButtonClicked:(id)arg1;
- (void)onIconFontButtonClick:(id)arg1;
- (void)awakeFromNib;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

